version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: strava_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: strava_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strava_api
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"
    command: ["./api"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strava_worker
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      REDIS_ADDR: redis:6379
    command: ["./worker"]

  asynqmon:
    image: hibiken/asynqmon
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "8081:8080"


volumes:
  postgres_data:
  redis_data: