# build stage
FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o api ./cmd/api
RUN go build -o worker ./cmd/worker

# runtime stage
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/api .
COPY --from=builder /app/worker .

EXPOSE 8080

CMD ["./api"]